apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-template.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-template.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }} 