apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-template.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-template.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.min }}
  selector:
    matchLabels:
      {{- include "go-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-template.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.security.runAsNonRoot }}
      securityContext:
        runAsNonRoot: {{ .Values.security.runAsNonRoot }}
        runAsUser: {{ .Values.security.runAsUser }}
        fsGroup: {{ .Values.security.fsGroup }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "go-template.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "go-template.fullname" . }}-config
        - secretRef:
            name: {{ include "go-template.fullname" . }}-secrets
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if and .Values.healthCheck .Values.healthCheck.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthCheck.livenessProbe.path }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.healthCheck.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.healthCheck.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.healthCheck.livenessProbe.failureThreshold }}
{{- if .Values.healthCheck.livenessProbe.successThreshold }}
          successThreshold: {{ .Values.healthCheck.livenessProbe.successThreshold }}
{{- end }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthCheck.readinessProbe.path }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.healthCheck.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.healthCheck.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.healthCheck.readinessProbe.failureThreshold }}
{{- if .Values.healthCheck.readinessProbe.successThreshold }}
          successThreshold: {{ .Values.healthCheck.readinessProbe.successThreshold }}
{{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 