{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "go-template.fullname" . }}-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-template.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "go-template.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      path: {{ .Values.metrics.path | default "/metrics" | quote }}
      interval: "30s"
      scheme: http
      scrapeTimeout: "10s"
{{- end }}
