apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-template.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-template.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: {{ .Values.metrics.path | quote }}
    prometheus.io/port: {{ .Values.metrics.port | toString | quote}}
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/interval: "30s"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
      {{- end }}
  selector:
    {{- include "go-template.selectorLabels" . | nindent 4 }}